---------------------------------------------------------------------->
-- 脚本名称:	scripts/Include/OnEnterSceneCommon/Player_EnterSceneCommon_Include.lua
-- 更新时间:	2017/3/20 19:38:42
-- 更新用户:	zhengfeng6
-- 脚本说明:
----------------------------------------------------------------------<
--注：新增Include都置顶，置顶，置顶，重要的事情说三遍！
Include("scripts/Map/拭剑园/include/拭剑园进出场景处理.lua")
Include("scripts/Map/世界通用/include/副本计数.lua")
Include("scripts/Map/ACT_元宵节/include/元宵节上下线处理.lua")
Include("scripts/Include/BattleField.lh")
Include("scripts/Map/世界奇遇/平生心愿/include/平生心愿_data.lh")
Include("scripts/Map/阵营首领/include/GFCampScoreData.lua")
Include("scripts/Map/阵营首领/include/大小攻防占坑.lua")
Include("scripts/Map/天山碎冰谷/include/登录.lua")
Include("scripts/Map/梦回稻香/include/梦回稻香头文件.lua")
Include("scripts/Map/世界奇遇/艺人奇遇/include/乱世舞姬_data.lua")
Include("scripts/Map/世界奇遇/绿林奇遇/include/Data.lua")
Include("scripts/Map/世界奇遇/护佑苍生/include/护佑苍生_data.lua")
Include("scripts/Map/江湖百态/方士/include/方士_Data.lua")
Include("scripts/Map/江湖百态/驭兽师/include/驭兽师_Data.lua")
Include("scripts/Map/江湖百态/include/IdentityBaseFunc.lua")
Include("scripts/Map/天山碎冰谷/include/arena_basefunc.lua")
Include("scripts/Map/跟宠系统/include/七秀兔子_data.lua")
Include("scripts/Map/世界奇遇/天涯无归/include/天涯无归_data.lua")
Include("scripts/Map/世界奇遇/梅花桩/include/梅花桩排名.lua")
Include("scripts/Map/世界奇遇/include/炼狱厨神_data.lua")
Include("scripts/Map/世界奇遇/宠物奇缘奇遇/include/捉妖记_data.lua")--【鱼头】
Include("scripts/Map/世界奇遇/宠物奇缘奇遇/include/红衣歌_data.lua")--【鱼头】
Include("scripts/Map/世界奇遇/宠物奇缘奇遇/include/枫林酒_data.lua")--【鱼头】
Include("scripts/Map/世界奇遇/宠物奇缘奇遇/include/孩童书_data.lua")--【鱼头】
Include("scripts/Map/世界奇遇/宠物奇缘奇遇/include/归乡路_data.lua")--【鱼头】
Include("scripts/Map/世界奇遇/宠物奇缘奇遇/include/胜负局_data.lua")--【鱼头】
Include("scripts/Map/世界奇遇/宠物奇缘奇遇/include/清茗经_data.lua")--【鱼头】
Include("scripts/Map/帮会押镖/include/帮会押镖.lh")
Include("scripts/Map/齐物阁/include/AllKill_Reward.lh")
Include("scripts/Map/帮会领地/include/TongDungeonRaid.lh")
Include("scripts/Map/世界奇遇/include/三尺青锋_data.lua")
Include("scripts/Map/世界通用/include/连续登陆签到翻牌奖励头文件.lh")
Include("scripts/Map/世界奇遇/茶馆奇缘/include/茶馆奇缘_Data.lua")
Include("scripts/Map/世界奇遇/黑白路/include/黑白路_Data.lua")
Include("scripts/Map/世界奇遇/include/寻宝_data.lua")
Include("scripts/Map/世界通用/include/FBTimeRankData.lua")
Include("scripts/Map/逐鹿中原/include/据点争夺_Data.lh")
Include("scripts/Map/逐鹿中原/include/据点贸易_Data.lh")
Include("scripts/Activity/活动开始结束处理/活动结束后任务设置为失败.lua")
Include("scripts/Map/ACT_押镖活动/include/EscortHead.lua")
Include("scripts/Map/ACT_门派入侵/skill/五毒_生死蛊复活玩家处理.lua")
Include("scripts/RandomQuest/帮会任务随机.lua")
Include("scripts/Map/寻宝系统/include/HoroSystem.lua")
Include("scripts/Map/科举考试/include/CivilServiceExamination.ls")
Include("scripts/Include/Time.lh")
Include("scripts/Include/Skill.lh")
Include("scripts/Include/Item.lh")
Include("scripts/Include/GlobalStrings.ls")
Include("scripts/Include/Dungeon.lh")
Include("scripts/Include/ClearCoolID.lh")
Include("scripts/Include/PlayerCustomValueName.lh")
Include("scripts/Activity/活动日历标记/include/ActivityMark.lh")
Include("scripts/Map/中秋节活动/skill/玩家死亡复活脚本.lua")
Include("scripts/Map/节日七夕/include/小月救人脚本.lua")
Include("scripts/Map/主城茶馆/include/茶馆任务处理.lua")
Include("scripts/Map/ACT_血战天策预热/include/奖励增益.lua")
Include("scripts/Map/世界通用/include/总控头文件.lh")
Include("scripts/Map/ACT_2014年3月预热/include/预热登陆加buff.lua")
Include("scripts/Map/驯养系统/include/卦板道具自损处理.lua")
Include("scripts/Map/逐鹿中原/include/otherfunctions.lua")
Include("scripts/Map/世界奇遇/include/阴阳两界_data.lua")
Include("scripts/Map/春节天街灯市/include/场景位面.lua")
 -- by 每天涨停@梦江南 $ Jx3UnPack-PAKV3 jx3.mail@gmail.com