

-- 这里是世界两两城市之间的价格,单位是铜
tCityCost = {
	luoyang_luodao = 2000, 
	changan_wanhua = 800, 
	heilongzhao_wuliangshan = 1000, 
	luoyang_jinshuizhen = 2000, 
	kunlunshan_erengu = 8500, 
	nanpingshan_luodao = 5000, 
	wudu_wuliangshan = 10000, 
	luoyang_tiance = 800, 
	yangzhou_luodao = 2000, 
	changan_chunyang = 800, 
	luoyang_shaolin = 800, 
	wudu_heilongzhao = 10000, 
	chengdu_wudu = 10000, 
	nanpingshan_haoqimeng = 8500, 
	luoyang_fenghuagu = 2000, 
	yangzhou_jinshuizhen = 2000, 
	bailongkou_chengdu = 10000, 
	kunlunshan_longmenhuangmo = 5000, 
	changjiangxiakou_bailongkou = 10000, 
	balingxian_changjiangxiakou = 5000, 
	balingxian_luodao = 5000, 
	bailongkou_wuliangshan = 10000, 
	changan_longmenhuangmo = 5000, 
	changan_fenghuagu = 2000, 
	rongtianling_heilongzhao = 10000, 
	wuliangshan_nanpingshan = 10000,  
	chengdu_rongtianling = 10000, 
	chengdu_tangmen = 10000,
	cangshanerhai_tangmen = 10000,
	mingjiao_longmenhuangmo = 10000,  --明教龙门
}

-- 这里的ID，对应MAPLIST中的ID对应的地图
tCityToString = {
	[2] = "wanhua",
	[5] = "shaolin",
	[6] = "yangzhou",
	[7] = "chunyang", 
	[8] = "luoyang", 
	[9] = "luodao", 
	[11] = "tiance",
	[12] = "fenghuagu", 
	[13] = "jinshuizhen", 
	[15] = "changan", 
	[23] = "longmenhuangmo",
	[30] = "kunlunshan", 
	[27] = "erengu", 
	[22] = "nanpingshan", 
	[25] = "haoqimeng", 
	[21] = "balingxian", 
	[35] = "changjiangxiakou", 
	[100] = "bailongkou",
	[101] = "wuliangshan",
	[102] = "wudu",
	[103] = "rongtianling",
	[104] = "heilongzhao",
	[105] = "cangshanerhai",
	[108] = "chengdu",
	[122] = "tangmen",
	[150] = "mingjiao", --明教
	--[200] = "luodao", --洛道使用了特殊的CITYID处理丁字路口问题。
}


-- 记录了从每一个城市出发，到达任意一个城市所需要路过的城市
tTrafficLine = {
	haoqimeng = {haoqimeng = "here", luodao = "nanpingshan/", luoyang = "nanpingshan/luodao", changjiangxiakou = "nanpingshan/luodao/balingxian", changan = "nanpingshan/luodao/luoyang/fenghuagu", fenghuagu = "nanpingshan/luodao/luoyang", shaolin = "nanpingshan/luodao/luoyang", wudu = "nanpingshan/wuliangshan/", nanpingshan = "neighbor/", chunyang = "nanpingshan/luodao/luoyang/fenghuagu/changan", heilongzhao = "nanpingshan/wuliangshan/wudu/", bailongkou = "nanpingshan/wuliangshan/", longmenhuangmo = "nanpingshan/luodao/luoyang/fenghuagu/changan", erengu = "nanpingshan/luodao/luoyang/fenghuagu/changan/longmenhuangmo/kunlunshan", chengdu = "nanpingshan/wuliangshan/wudu/", rongtianling = "nanpingshan/wuliangshan/wudu/heilongzhao/", wuliangshan = "nanpingshan/", yangzhou = "nanpingshan/luodao", jinshuizhen = "nanpingshan/luodao/luoyang", tiance = "nanpingshan/luodao/luoyang", kunlunshan = "nanpingshan/luodao/luoyang/fenghuagu/changan/longmenhuangmo", balingxian = "nanpingshan/luodao", wanhua = "nanpingshan/luodao/luoyang/fenghuagu/changan", },
	luodao = {haoqimeng = "nanpingshan/", luodao = "here", luoyang = "neighbor/", changjiangxiakou = "balingxian/", changan = "luoyang/fenghuagu", fenghuagu = "luoyang/", shaolin = "luoyang/", wudu = "nanpingshan/wuliangshan/", nanpingshan = "neighbor/", chunyang = "luoyang/fenghuagu/changan", heilongzhao = "nanpingshan/wuliangshan/wudu/", bailongkou = "balingxian/changjiangxiakou/", longmenhuangmo = "luoyang/fenghuagu/changan", erengu = "luoyang/fenghuagu/changan/longmenhuangmo/kunlunshan", chengdu = "balingxian/changjiangxiakou/bailongkou/", rongtianling = "balingxian/changjiangxiakou/bailongkou/chengdu/", wuliangshan = "nanpingshan/", yangzhou = "neighbor/", jinshuizhen = "luoyang/", tiance = "luoyang/", kunlunshan = "luoyang/fenghuagu/changan/longmenhuangmo", balingxian = "neighbor/", wanhua = "luoyang/fenghuagu/changan", },
	jinshuizhen = {haoqimeng = "luoyang/luodao/nanpingshan", luodao = "luoyang/", luoyang = "neighbor/", changjiangxiakou = "luoyang/luodao/balingxian", changan = "luoyang/fenghuagu", fenghuagu = "luoyang/", shaolin = "luoyang/", wudu = "luoyang/luodao/nanpingshan/wuliangshan/", nanpingshan = "luoyang/luodao", chunyang = "luoyang/fenghuagu/changan", heilongzhao = "luoyang/luodao/nanpingshan/wuliangshan/wudu/", bailongkou = "luoyang/luodao/balingxian/changjiangxiakou/", longmenhuangmo = "luoyang/fenghuagu/changan", erengu = "luoyang/fenghuagu/changan/longmenhuangmo/kunlunshan", chengdu = "luoyang/luodao/balingxian/changjiangxiakou/bailongkou/", rongtianling = "luoyang/luodao/balingxian/changjiangxiakou/bailongkou/chengdu/", wuliangshan = "luoyang/luodao/nanpingshan/", yangzhou = "neighbor/", jinshuizhen = "here", tiance = "luoyang/", kunlunshan = "luoyang/fenghuagu/changan/longmenhuangmo", balingxian = "luoyang/luodao", wanhua = "luoyang/fenghuagu/changan", },
	changjiangxiakou = {haoqimeng = "balingxian/luodao/nanpingshan", luodao = "balingxian/", luoyang = "balingxian/luodao", changjiangxiakou = "here", changan = "balingxian/luodao/luoyang/fenghuagu/", fenghuagu = "balingxian/luodao/luoyang", shaolin = "balingxian/luodao/luoyang", wudu = "bailongkou/wuliangshan/", nanpingshan = "balingxian/luodao", chunyang = "balingxian/luodao/luoyang/fenghuagu/changan", heilongzhao = "bailongkou/wuliangshan/wudu/", bailongkou = "neighbor/", longmenhuangmo = "balingxian/luodao/luoyang/fenghuagu/changan", erengu = "balingxian/luodao/luoyang/fenghuagu/changan/longmenhuangmo/kunlunshan", chengdu = "bailongkou/", rongtianling = "bailongkou/chengdu/", wuliangshan = "bailongkou/", yangzhou = "balingxian/luodao", jinshuizhen = "balingxian/luodao/luoyang", tiance = "balingxian/luodao/luoyang", kunlunshan = "balingxian/luodao/luoyang/fenghuagu/changan/longmenhuangmo", balingxian = "neighbor/", wanhua = "balingxian/luodao/luoyang/fenghuagu/changan", },
	changan = {haoqimeng = "fenghuagu/luoyang/luodao/nanpingshan", luodao = "fenghuagu/luoyang", luoyang = "fenghuagu/", changjiangxiakou = "fenghuagu/luoyang/luodao/balingxian", changan = "here", fenghuagu = "neighbor/", shaolin = "fenghuagu/luoyang", wudu = "fenghuagu/luoyang/luodao/nanpingshan/wuliangshan/", nanpingshan = "fenghuagu/luoyang/luodao", chunyang = "neighbor/", heilongzhao = "fenghuagu/luoyang/luodao/nanpingshan/wuliangshan/wudu/", bailongkou = "fenghuagu/luoyang/luodao/balingxian/changjiangxiakou/", longmenhuangmo = "neighbor/", erengu = "longmenhuangmo/kunlunshan", chengdu = "fenghuagu/luoyang/luodao/balingxian/changjiangxiakou/bailongkou/", rongtianling = "fenghuagu/luoyang/luodao/balingxian/changjiangxiakou/bailongkou/chengdu/", wuliangshan = "fenghuagu/luoyang/luodao/nanpingshan/", yangzhou = "fenghuagu/luoyang/jinshuizhen", jinshuizhen = "fenghuagu/luoyang", tiance = "fenghuagu/luoyang", kunlunshan = "longmenhuangmo/", balingxian = "fenghuagu/luoyang/luodao", wanhua = "neighbor/", },
	fenghuagu = {haoqimeng = "luoyang/luodao/nanpingshan", luodao = "luoyang/", luoyang = "neighbor/", changjiangxiakou = "luoyang/luodao/balingxian", changan = "neighbor/", fenghuagu = "here", shaolin = "luoyang/", wudu = "luoyang/luodao/nanpingshan/wuliangshan/", nanpingshan = "luoyang/luodao", chunyang = "changan/", heilongzhao = "luoyang/luodao/nanpingshan/wuliangshan/wudu/", bailongkou = "luoyang/luodao/balingxian/changjiangxiakou/", longmenhuangmo = "changan/", erengu = "changan/longmenhuangmo/kunlunshan", chengdu = "luoyang/luodao/balingxian/changjiangxiakou/bailongkou/", rongtianling = "luoyang/luodao/balingxian/changjiangxiakou/bailongkou/chengdu/", wuliangshan = "luoyang/luodao/nanpingshan/", yangzhou = "luoyang/jinshuizhen", jinshuizhen = "luoyang/", tiance = "luoyang/", kunlunshan = "changan/longmenhuangmo", balingxian = "luoyang/luodao", wanhua = "changan/", },
	shaolin = {haoqimeng = "luoyang/luodao/nanpingshan", luodao = "luoyang/", luoyang = "neighbor/", changjiangxiakou = "luoyang/luodao/balingxian", changan = "luoyang/fenghuagu/", fenghuagu = "luoyang/", shaolin = "here", wudu = "luoyang/luodao/nanpingshan/wuliangshan/", nanpingshan = "luoyang/luodao/", chunyang = "luoyang/fenghuagu/changan", heilongzhao = "luoyang/luodao/nanpingshan/wuliangshan/wudu/", bailongkou = "luoyang/luodao/balingxian/changjiangxiakou/", longmenhuangmo = "luoyang/fenghuagu/changan", erengu = "luoyang/fenghuagu/changan/longmenhuangmo/kunlunshan", chengdu = "luoyang/luodao/balingxian/changjiangxiakou/bailongkou/", rongtianling = "luoyang/luodao/balingxian/changjiangxiakou/bailongkou/chengdu/", wuliangshan = "luoyang/luodao/nanpingshan/", yangzhou = "luoyang/jinshuizhen/", jinshuizhen = "luoyang/", tiance = "luoyang/", kunlunshan = "luoyang/fenghuagu/changan/longmenhuangmo", balingxian = "luoyang/luodao/", wanhua = "luoyang/fenghuagu/changan", },
	wudu = {haoqimeng = "wuliangshan/nanpingshan/", luodao = "wuliangshan/nanpingshan/", luoyang = "wuliangshan/nanpingshan/luodao/", changjiangxiakou = "wuliangshan/bailongkou/", changan = "wuliangshan/nanpingshan/luodao/luoyang/fenghuagu/", fenghuagu = "wuliangshan/nanpingshan/luodao/luoyang/", shaolin = "wuliangshan/nanpingshan/luodao/luoyang/", wudu = "here", nanpingshan = "wuliangshan/", chunyang = "wuliangshan/nanpingshan/luodao/luoyang/fenghuagu/changan/", heilongzhao = "neighbor/", bailongkou = "wuliangshan/", longmenhuangmo = "wuliangshan/nanpingshan/luodao/luoyang/fenghuagu/changan/", wanhua = "wuliangshan/nanpingshan/luodao/luoyang/fenghuagu/changan/", chengdu = "neighbor/", rongtianling = "heilongzhao/", wuliangshan = "neighbor/", yangzhou = "wuliangshan/nanpingshan/luodao/", erengu = "wuliangshan/nanpingshan/luodao/luoyang/fenghuagu/changan/longmenhuangmo/kunlunshan/", tiance = "wuliangshan/nanpingshan/luodao/luoyang/", kunlunshan = "wuliangshan/nanpingshan/luodao/luoyang/fenghuagu/changan/longmenhuangmo/", balingxian = "wuliangshan/nanpingshan/luodao/", jinshuizhen = "wuliangshan/nanpingshan/luodao/luoyang/", },
	nanpingshan = {haoqimeng = "neighbor/", luodao = "neighbor/", luoyang = "luodao/", changjiangxiakou = "luodao/balingxian", changan = "luodao/luoyang/fenghuagu", fenghuagu = "luodao/luoyang", shaolin = "luodao/luoyang", wudu = "wuliangshan/", nanpingshan = "here", chunyang = "luodao/luoyang/fenghuagu/changan", heilongzhao = "wuliangshan/wudu/", bailongkou = "wuliangshan/", longmenhuangmo = "luodao/luoyang/fenghuagu/changan", erengu = "luodao/luoyang/fenghuagu/changan/longmenhuangmo/kunlunshan", chengdu = "wuliangshan/wudu/", rongtianling = "wuliangshan/wudu/heilongzhao/", wuliangshan = "neighbor/", yangzhou = "luodao/", jinshuizhen = "luodao/luoyang", tiance = "luodao/luoyang", kunlunshan = "luodao/luoyang/fenghuagu/changan/longmenhuangmo", balingxian = "luodao/", wanhua = "luodao/luoyang/fenghuagu/changan", },
	chunyang = {haoqimeng = "changan/fenghuagu/luoyang/luodao/nanpingshan", luodao = "changan/fenghuagu/luoyang", luoyang = "changan/fenghuagu", changjiangxiakou = "changan/fenghuagu/luoyang/luodao/balingxian", changan = "neighbor/", fenghuagu = "changan/", shaolin = "changan/fenghuagu/luoyang", wudu = "changan/fenghuagu/luoyang/luodao/nanpingshan/wuliangshan/", nanpingshan = "changan/fenghuagu/luoyang/luodao", chunyang = "here", heilongzhao = "changan/fenghuagu/luoyang/luodao/nanpingshan/wuliangshan/wudu/", bailongkou = "changan/fenghuagu/luoyang/luodao/balingxian/changjiangxiakou/", longmenhuangmo = "changan/", erengu = "changan/longmenhuangmo/kunlunshan", chengdu = "changan/fenghuagu/luoyang/luodao/balingxian/changjiangxiakou/bailongkou/", rongtianling = "changan/fenghuagu/luoyang/luodao/balingxian/changjiangxiakou/bailongkou/chengdu/", wuliangshan = "changan/fenghuagu/luoyang/luodao/nanpingshan/", yangzhou = "changan/fenghuagu/luoyang/jinshuizhen", jinshuizhen = "changan/fenghuagu/luoyang", tiance = "changan/fenghuagu/luoyang", kunlunshan = "changan/longmenhuangmo/", balingxian = "changan/fenghuagu/luoyang/luodao", wanhua = "changan/", },
	heilongzhao = {haoqimeng = "wudu/wuliangshan/nanpingshan/", luodao = "wudu/wuliangshan/nanpingshan/", luoyang = "wudu/wuliangshan/nanpingshan/luodao/", changjiangxiakou = "rongtianling/chengdu/bailongkou/", changan = "wudu/wuliangshan/nanpingshan/luodao/luoyang/fenghuagu/", fenghuagu = "wudu/wuliangshan/nanpingshan/luodao/luoyang/", shaolin = "wudu/wuliangshan/nanpingshan/luodao/luoyang/", wudu = "neighbor/", nanpingshan = "wudu/wuliangshan/", chunyang = "wudu/wuliangshan/nanpingshan/luodao/luoyang/fenghuagu/changan/", heilongzhao = "here", bailongkou = "rongtianling/chengdu/", longmenhuangmo = "wudu/wuliangshan/nanpingshan/luodao/luoyang/fenghuagu/changan/", wanhua = "wudu/wuliangshan/nanpingshan/luodao/luoyang/fenghuagu/changan/", chengdu = "rongtianling/", rongtianling = "neighbor/", wuliangshan = "wudu/", yangzhou = "wudu/wuliangshan/nanpingshan/luodao/", erengu = "wudu/wuliangshan/nanpingshan/luodao/luoyang/fenghuagu/changan/longmenhuangmo/kunlunshan/", tiance = "wudu/wuliangshan/nanpingshan/luodao/luoyang/", kunlunshan = "wudu/wuliangshan/nanpingshan/luodao/luoyang/fenghuagu/changan/longmenhuangmo/", balingxian = "wudu/wuliangshan/nanpingshan/luodao/", jinshuizhen = "wudu/wuliangshan/nanpingshan/luodao/luoyang/", },
	bailongkou = {haoqimeng = "wuliangshan/nanpingshan/", luodao = "changjiangxiakou/balingxian/", luoyang = "changjiangxiakou/balingxian/luodao/", changjiangxiakou = "neighbor/", changan = "changjiangxiakou/balingxian/luodao/luoyang/fenghuagu/", fenghuagu = "changjiangxiakou/balingxian/luodao/luoyang/", shaolin = "changjiangxiakou/balingxian/luodao/luoyang/", wudu = "wuliangshan/", nanpingshan = "wuliangshan/", chunyang = "changjiangxiakou/balingxian/luodao/luoyang/fenghuagu/changan/", heilongzhao = "wuliangshan/wudu/", bailongkou = "here", longmenhuangmo = "changjiangxiakou/balingxian/luodao/luoyang/fenghuagu/changan/", wanhua = "changjiangxiakou/balingxian/luodao/luoyang/fenghuagu/changan/", chengdu = "neighbor/", rongtianling = "chengdu/", wuliangshan = "neighbor/", yangzhou = "changjiangxiakou/balingxian/luodao/", erengu = "changjiangxiakou/balingxian/luodao/luoyang/fenghuagu/changan/longmenhuangmo/kunlunshan/", tiance = "changjiangxiakou/balingxian/luodao/luoyang/", kunlunshan = "changjiangxiakou/balingxian/luodao/luoyang/fenghuagu/changan/longmenhuangmo/", balingxian = "changjiangxiakou/", jinshuizhen = "changjiangxiakou/balingxian/luodao/luoyang/", },
	longmenhuangmo = {haoqimeng = "changan/fenghuagu/luoyang/luodao/nanpingshan", luodao = "changan/fenghuagu/luoyang", luoyang = "changan/fenghuagu", changjiangxiakou = "changan/fenghuagu/luoyang/luodao/balingxian", changan = "neighbor/", mingjiao = "neighbor/",fenghuagu = "changan/", shaolin = "changan/fenghuagu/luoyang", wudu = "changan/fenghuagu/luoyang/luodao/nanpingshan/wuliangshan/", nanpingshan = "changan/fenghuagu/luoyang/luodao", chunyang = "changan/", heilongzhao = "changan/fenghuagu/luoyang/luodao/nanpingshan/wuliangshan/wudu/", bailongkou = "changan/fenghuagu/luoyang/luodao/balingxian/changjiangxiakou/", longmenhuangmo = "here", erengu = "kunlunshan/", chengdu = "changan/fenghuagu/luoyang/luodao/balingxian/changjiangxiakou/bailongkou/", rongtianling = "changan/fenghuagu/luoyang/luodao/balingxian/changjiangxiakou/bailongkou/chengdu/", wuliangshan = "changan/fenghuagu/luoyang/luodao/nanpingshan/", yangzhou = "changan/fenghuagu/luoyang/jinshuizhen", jinshuizhen = "changan/fenghuagu/luoyang", tiance = "changan/fenghuagu/luoyang", kunlunshan = "neighbor/", balingxian = "changan/fenghuagu/luoyang/luodao", wanhua = "changan/", },
	erengu = {haoqimeng = "kunlunshan/longmenhuangmo/changan/fenghuagu/luoyang/luodao/nanpingshan", luodao = "kunlunshan/longmenhuangmo/changan/fenghuagu/luoyang", luoyang = "kunlunshan/longmenhuangmo/changan/fenghuagu", changjiangxiakou = "kunlunshan/longmenhuangmo/changan/fenghuagu/luoyang/luodao/balingxian", changan = "kunlunshan/longmenhuangmo", fenghuagu = "kunlunshan/longmenhuangmo/changan", shaolin = "kunlunshan/longmenhuangmo/changan/fenghuagu/luoyang", wudu = "kunlunshan/longmenhuangmo/changan/fenghuagu/luoyang/luodao/nanpingshan/wuliangshan/", nanpingshan = "kunlunshan/longmenhuangmo/changan/fenghuagu/luoyang/luodao", chunyang = "kunlunshan/longmenhuangmo/changan", heilongzhao = "kunlunshan/longmenhuangmo/changan/fenghuagu/luoyang/luodao/nanpingshan/wuliangshan/wudu/", bailongkou = "kunlunshan/longmenhuangmo/changan/fenghuagu/luoyang/luodao/balingxian/changjiangxiakou/", longmenhuangmo = "kunlunshan/", erengu = "here", chengdu = "kunlunshan/longmenhuangmo/changan/fenghuagu/luoyang/luodao/balingxian/changjiangxiakou/bailongkou/", rongtianling = "kunlunshan/longmenhuangmo/changan/fenghuagu/luoyang/luodao/balingxian/changjiangxiakou/bailongkou/chengdu/", wuliangshan = "kunlunshan/longmenhuangmo/changan/fenghuagu/luoyang/luodao/nanpingshan/", yangzhou = "kunlunshan/longmenhuangmo/changan/fenghuagu/luoyang/jinshuizhen", jinshuizhen = "kunlunshan/longmenhuangmo/changan/fenghuagu/luoyang", tiance = "kunlunshan/longmenhuangmo/changan/fenghuagu/luoyang", kunlunshan = "neighbor/", balingxian = "kunlunshan/longmenhuangmo/changan/fenghuagu/luoyang/luodao", wanhua = "kunlunshan/longmenhuangmo/changan", },
	chengdu = {haoqimeng = "wudu/wuliangshan/nanpingshan/", luodao = "bailongkou/changjiangxiakou/balingxian/", luoyang = "bailongkou/changjiangxiakou/balingxian/luodao/", changjiangxiakou = "bailongkou/", changan = "bailongkou/changjiangxiakou/balingxian/luodao/luoyang/fenghuagu/", fenghuagu = "bailongkou/changjiangxiakou/balingxian/luodao/luoyang/", shaolin = "bailongkou/changjiangxiakou/balingxian/luodao/luoyang/", wudu = "neighbor/", nanpingshan = "wudu/wuliangshan/", chunyang = "bailongkou/changjiangxiakou/balingxian/luodao/luoyang/fenghuagu/changan/", heilongzhao = "rongtianling/", bailongkou = "neighbor/", longmenhuangmo = "bailongkou/changjiangxiakou/balingxian/luodao/luoyang/fenghuagu/changan/", wanhua = "bailongkou/changjiangxiakou/balingxian/luodao/luoyang/fenghuagu/changan/", chengdu = "here", rongtianling = "neighbor/", wuliangshan = "bailongkou/", yangzhou = "bailongkou/changjiangxiakou/balingxian/luodao/", erengu = "bailongkou/changjiangxiakou/balingxian/luodao/luoyang/fenghuagu/changan/longmenhuangmo/kunlunshan/", tiance = "bailongkou/changjiangxiakou/balingxian/luodao/luoyang/", kunlunshan = "bailongkou/changjiangxiakou/balingxian/luodao/luoyang/fenghuagu/changan/longmenhuangmo/", balingxian = "bailongkou/changjiangxiakou/", jinshuizhen = "bailongkou/changjiangxiakou/balingxian/luodao/luoyang/", },
	rongtianling = {haoqimeng = "heilongzhao/wudu/wuliangshan/nanpingshan/", luodao = "chengdu/bailongkou/changjiangxiakou/balingxian/", luoyang = "chengdu/bailongkou/changjiangxiakou/balingxian/luodao/", changjiangxiakou = "chengdu/bailongkou/", changan = "chengdu/bailongkou/changjiangxiakou/balingxian/luodao/luoyang/fenghuagu/", fenghuagu = "chengdu/bailongkou/changjiangxiakou/balingxian/luodao/luoyang/", shaolin = "chengdu/bailongkou/changjiangxiakou/balingxian/luodao/luoyang/", wudu = "heilongzhao/", nanpingshan = "heilongzhao/wudu/wuliangshan/", chunyang = "chengdu/bailongkou/changjiangxiakou/balingxian/luodao/luoyang/fenghuagu/changan/", heilongzhao = "neighbor/", bailongkou = "chengdu/", longmenhuangmo = "chengdu/bailongkou/changjiangxiakou/balingxian/luodao/luoyang/fenghuagu/changan/", wanhua = "chengdu/bailongkou/changjiangxiakou/balingxian/luodao/luoyang/fenghuagu/changan/", chengdu = "neighbor/", rongtianling = "here", wuliangshan = "heilongzhao/wudu/", yangzhou = "chengdu/bailongkou/changjiangxiakou/balingxian/luodao/", erengu = "chengdu/bailongkou/changjiangxiakou/balingxian/luodao/luoyang/fenghuagu/changan/longmenhuangmo/kunlunshan/", tiance = "chengdu/bailongkou/changjiangxiakou/balingxian/luodao/luoyang/", kunlunshan = "chengdu/bailongkou/changjiangxiakou/balingxian/luodao/luoyang/fenghuagu/changan/longmenhuangmo/", balingxian = "chengdu/bailongkou/changjiangxiakou/", jinshuizhen = "chengdu/bailongkou/changjiangxiakou/balingxian/luodao/luoyang/", },
	wuliangshan = {haoqimeng = "nanpingshan/", luodao = "nanpingshan/", luoyang = "nanpingshan/luodao/", changjiangxiakou = "bailongkou/", changan = "nanpingshan/luodao/luoyang/fenghuagu/", fenghuagu = "nanpingshan/luodao/luoyang/", shaolin = "nanpingshan/luodao/luoyang/", wudu = "neighbor/", nanpingshan = "neighbor/", chunyang = "nanpingshan/luodao/luoyang/fenghuagu/changan/", heilongzhao = "wudu/", bailongkou = "neighbor/", longmenhuangmo = "nanpingshan/luodao/luoyang/fenghuagu/changan/", wanhua = "nanpingshan/luodao/luoyang/fenghuagu/changan/", chengdu = "wudu/", rongtianling = "wudu/heilongzhao/", wuliangshan = "here", yangzhou = "nanpingshan/luodao/", erengu = "nanpingshan/luodao/luoyang/fenghuagu/changan/longmenhuangmo/kunlunshan/", tiance = "nanpingshan/luodao/luoyang/", kunlunshan = "nanpingshan/luodao/luoyang/fenghuagu/changan/longmenhuangmo/", balingxian = "nanpingshan/luodao/", jinshuizhen = "nanpingshan/luodao/luoyang/", },
	yangzhou = {haoqimeng = "luodao/nanpingshan", luodao = "neighbor/", luoyang = "jinshuizhen/", changjiangxiakou = "luodao/balingxian", changan = "jinshuizhen/luoyang/fenghuagu", fenghuagu = "jinshuizhen/luoyang", shaolin = "jinshuizhen/luoyang", wudu = "luodao/nanpingshan/wuliangshan/", nanpingshan = "luodao/", chunyang = "jinshuizhen/luoyang/fenghuagu/changan", heilongzhao = "luodao/nanpingshan/wuliangshan/wudu/", bailongkou = "luodao/balingxian/changjiangxiakou/", longmenhuangmo = "jinshuizhen/luoyang/fenghuagu/changan", erengu = "jinshuizhen/luoyang/fenghuagu/changan/longmenhuangmo/kunlunshan", chengdu = "luodao/balingxian/changjiangxiakou/bailongkou/", rongtianling = "luodao/balingxian/changjiangxiakou/bailongkou/chengdu/", wuliangshan = "luodao/nanpingshan/", yangzhou = "here", jinshuizhen = "neighbor/", tiance = "jinshuizhen/luoyang", kunlunshan = "jinshuizhen/luoyang/fenghuagu/changan/longmenhuangmo", balingxian = "luodao/", wanhua = "jinshuizhen/luoyang/fenghuagu/changan", },
	balingxian = {haoqimeng = "luodao/nanpingshan", luodao = "neighbor/", luoyang = "luodao/", changjiangxiakou = "neighbor/", changan = "luodao/luoyang/fenghuagu", fenghuagu = "luodao/luoyang", shaolin = "luodao/luoyang", wudu = "luodao/nanpingshan/wuliangshan/", nanpingshan = "luodao/", chunyang = "luodao/luoyang/fenghuagu/changan", heilongzhao = "luodao/nanpingshan/wuliangshan/wudu/", bailongkou = "changjiangxiakou/", longmenhuangmo = "luodao/luoyang/fenghuagu/changan", erengu = "luodao/luoyang/fenghuagu/changan/longmenhuangmo/kunlunshan", chengdu = "changjiangxiakou/bailongkou/", rongtianling = "changjiangxiakou/bailongkou/chengdu/", wuliangshan = "luodao/nanpingshan/", yangzhou = "luodao/", jinshuizhen = "luodao/luoyang", tiance = "luodao/luoyang", kunlunshan = "luodao/luoyang/fenghuagu/changan/longmenhuangmo", balingxian = "here", wanhua = "luodao/luoyang/fenghuagu/changan", },
	tiance = {haoqimeng = "luoyang/luodao/nanpingshan", luodao = "luoyang/", luoyang = "neighbor/", changjiangxiakou = "luoyang/luodao/balingxian", changan = "luoyang/fenghuagu/", fenghuagu = "luoyang/", shaolin = "luoyang/", wudu = "luoyang/luodao/nanpingshan/wuliangshan/", nanpingshan = "luoyang/luodao/", chunyang = "luoyang/fenghuagu/changan", heilongzhao = "luoyang/luodao/nanpingshan/wuliangshan/wudu/", bailongkou = "luoyang/luodao/balingxian/changjiangxiakou/", longmenhuangmo = "luoyang/fenghuagu/changan", erengu = "luoyang/fenghuagu/changan/longmenhuangmo/kunlunshan", chengdu = "luoyang/luodao/balingxian/changjiangxiakou/bailongkou/", rongtianling = "luoyang/luodao/balingxian/changjiangxiakou/bailongkou/chengdu/", wuliangshan = "luoyang/luodao/nanpingshan/", yangzhou = "luoyang/jinshuizhen/", jinshuizhen = "luoyang/", tiance = "here", kunlunshan = "luoyang/fenghuagu/changan/longmenhuangmo", balingxian = "luoyang/luodao/", wanhua = "luoyang/fenghuagu/changan", },
	kunlunshan = {haoqimeng = "longmenhuangmo/changan/fenghuagu/luoyang/luodao/nanpingshan", luodao = "longmenhuangmo/changan/fenghuagu/luoyang", luoyang = "longmenhuangmo/changan/fenghuagu", changjiangxiakou = "longmenhuangmo/changan/fenghuagu/luoyang/luodao/balingxian", changan = "longmenhuangmo/", fenghuagu = "longmenhuangmo/changan", shaolin = "longmenhuangmo/changan/fenghuagu/luoyang", wudu = "longmenhuangmo/changan/fenghuagu/luoyang/luodao/nanpingshan/wuliangshan/", nanpingshan = "longmenhuangmo/changan/fenghuagu/luoyang/luodao", chunyang = "longmenhuangmo/changan", heilongzhao = "longmenhuangmo/changan/fenghuagu/luoyang/luodao/nanpingshan/wuliangshan/wudu/", bailongkou = "longmenhuangmo/changan/fenghuagu/luoyang/luodao/balingxian/changjiangxiakou/", longmenhuangmo = "neighbor/", erengu = "neighbor/", chengdu = "longmenhuangmo/changan/fenghuagu/luoyang/luodao/balingxian/changjiangxiakou/bailongkou/", rongtianling = "longmenhuangmo/changan/fenghuagu/luoyang/luodao/balingxian/changjiangxiakou/bailongkou/chengdu/", wuliangshan = "longmenhuangmo/changan/fenghuagu/luoyang/luodao/nanpingshan/", yangzhou = "longmenhuangmo/changan/fenghuagu/luoyang/jinshuizhen", jinshuizhen = "longmenhuangmo/changan/fenghuagu/luoyang", tiance = "longmenhuangmo/changan/fenghuagu/luoyang", kunlunshan = "here", balingxian = "longmenhuangmo/changan/fenghuagu/luoyang/luodao", wanhua = "longmenhuangmo/changan", },
	luoyang = {haoqimeng = "luodao/nanpingshan", luodao = "neighbor/", luoyang = "here", changjiangxiakou = "luodao/balingxian", changan = "fenghuagu/", fenghuagu = "neighbor/", shaolin = "neighbor/", wudu = "luodao/nanpingshan/wuliangshan/", nanpingshan = "luodao/", chunyang = "fenghuagu/changan", heilongzhao = "luodao/nanpingshan/wuliangshan/wudu/", bailongkou = "luodao/balingxian/changjiangxiakou/", longmenhuangmo = "fenghuagu/changan", erengu = "fenghuagu/changan/longmenhuangmo/kunlunshan", chengdu = "luodao/balingxian/changjiangxiakou/bailongkou/", rongtianling = "luodao/balingxian/changjiangxiakou/bailongkou/chengdu/", wuliangshan = "luodao/nanpingshan/", yangzhou = "jinshuizhen/", jinshuizhen = "neighbor/", tiance = "neighbor/", kunlunshan = "fenghuagu/changan/longmenhuangmo", balingxian = "luodao/", wanhua = "fenghuagu/changan", },
	wanhua = {haoqimeng = "changan/fenghuagu/luoyang/luodao/nanpingshan", luodao = "changan/fenghuagu/luoyang", luoyang = "changan/fenghuagu", changjiangxiakou = "changan/fenghuagu/luoyang/luodao/balingxian", changan = "neighbor/", fenghuagu = "changan/", shaolin = "changan/fenghuagu/luoyang", wudu = "changan/fenghuagu/luoyang/luodao/nanpingshan/wuliangshan/", nanpingshan = "changan/fenghuagu/luoyang/luodao", chunyang = "changan/", heilongzhao = "changan/fenghuagu/luoyang/luodao/nanpingshan/wuliangshan/wudu/", bailongkou = "changan/fenghuagu/luoyang/luodao/balingxian/changjiangxiakou/", longmenhuangmo = "changan/", erengu = "changan/longmenhuangmo/kunlunshan", chengdu = "changan/fenghuagu/luoyang/luodao/balingxian/changjiangxiakou/bailongkou/", rongtianling = "changan/fenghuagu/luoyang/luodao/balingxian/changjiangxiakou/bailongkou/chengdu/", wuliangshan = "changan/fenghuagu/luoyang/luodao/nanpingshan/", yangzhou = "changan/fenghuagu/luoyang/jinshuizhen", jinshuizhen = "changan/fenghuagu/luoyang", tiance = "changan/fenghuagu/luoyang", kunlunshan = "changan/longmenhuangmo/", balingxian = "changan/fenghuagu/luoyang/luodao", wanhua = "here", },

}

 -- by 每天涨停@梦江南 $ Jx3UnPack-PAKV3 jx3.mail@gmail.com