g_AIParam[6507] = {IsPositive = 1,AlertRange = 768,SearchPlayerDistance = 768,AlertOverTime = 32,AttackRange = 256,EscapeTime = 64,EscapeRange = 0,EscapeInterval = 32,WanderRange = 0,WanderDistance = 384,WanderInterval = 80,PatrolPathID = 0,EscapeLife = 0,PatrolOrderIndex = 0,ReviveTeammate = 0,IsAutoTurn = 1,NpcSceneType = 0,IsSnarlInFight = 1,DialogIdleTime = 320,}
g_AIParam[6508] = {IsPositive = 1,AlertRange = 768,SearchPlayerDistance = 768,AlertOverTime = 32,AttackRange = 256,EscapeTime = 64,EscapeRange = 0,EscapeInterval = 32,WanderRange = 0,WanderDistance = 384,WanderInterval = 80,PatrolPathID = 0,EscapeLife = 0,PatrolOrderIndex = 0,ReviveTeammate = 0,IsAutoTurn = 1,NpcSceneType = 0,IsSnarlInFight = 1,DialogIdleTime = 320,}
g_AIParam[6509] = {IsPositive = 1,AlertRange = 768,SearchPlayerDistance = 768,AlertOverTime = 32,AttackRange = 256,EscapeTime = 64,EscapeRange = 0,EscapeInterval = 32,WanderRange = 0,WanderDistance = 384,WanderInterval = 80,PatrolPathID = 0,EscapeLife = 0,PatrolOrderIndex = 0,ReviveTeammate = 0,IsAutoTurn = 1,NpcSceneType = 0,IsSnarlInFight = 1,DialogIdleTime = 320,}
g_AIParam[6510] = {IsPositive = 1,AlertRange = 768,SearchPlayerDistance = 768,AlertOverTime = 32,AttackRange = 256,EscapeTime = 64,EscapeRange = 0,EscapeInterval = 32,WanderRange = 0,WanderDistance = 384,WanderInterval = 80,PatrolPathID = 0,EscapeLife = 0,PatrolOrderIndex = 0,ReviveTeammate = 0,IsAutoTurn = 1,NpcSceneType = 0,IsSnarlInFight = 1,DialogIdleTime = 320,}
g_AIParam[6511] = {IsPositive = 1,AlertRange = 768,SearchPlayerDistance = 768,AlertOverTime = 32,AttackRange = 256,EscapeTime = 64,EscapeRange = 0,EscapeInterval = 32,WanderRange = 0,WanderDistance = 384,WanderInterval = 80,PatrolPathID = 0,EscapeLife = 0,PatrolOrderIndex = 0,ReviveTeammate = 0,IsAutoTurn = 1,NpcSceneType = 0,IsSnarlInFight = 1,DialogIdleTime = 320,}
g_AIParam[6512] = {IsPositive = 1,AlertRange = 768,SearchPlayerDistance = 768,AlertOverTime = 32,AttackRange = 256,EscapeTime = 64,EscapeRange = 0,EscapeInterval = 32,WanderRange = 0,WanderDistance = 384,WanderInterval = 80,PatrolPathID = 0,EscapeLife = 0,PatrolOrderIndex = 0,ReviveTeammate = 0,IsAutoTurn = 1,NpcSceneType = 0,IsSnarlInFight = 1,DialogIdleTime = 320,}
g_AIParam[6513] = {IsPositive = 0,AlertRange = 768,SearchPlayerDistance = 768,AlertOverTime = 32,AttackRange = 256,EscapeTime = 64,EscapeRange = 0,EscapeInterval = 32,WanderRange = 0,WanderDistance = 384,WanderInterval = 80,PatrolPathID = 0,EscapeLife = 0,PatrolOrderIndex = 0,ReviveTeammate = 0,IsAutoTurn = 1,NpcSceneType = 0,IsSnarlInFight = 0,DialogIdleTime = 320,}
g_AIParam[6514] = {IsPositive = 0,AlertRange = 768,SearchPlayerDistance = 768,AlertOverTime = 32,AttackRange = 256,EscapeTime = 64,EscapeRange = 0,EscapeInterval = 32,WanderRange = 0,WanderDistance = 384,WanderInterval = 80,PatrolPathID = 0,EscapeLife = 0,PatrolOrderIndex = 0,ReviveTeammate = 0,IsAutoTurn = 1,NpcSceneType = 0,IsSnarlInFight = 0,DialogIdleTime = 320,}
g_AIParam[6515] = {IsPositive = 1,AlertRange = 768,SearchPlayerDistance = 768,AlertOverTime = 32,AttackRange = 256,EscapeTime = 64,EscapeRange = 0,EscapeInterval = 32,WanderRange = 0,WanderDistance = 384,WanderInterval = 80,PatrolPathID = 0,EscapeLife = 0,PatrolOrderIndex = 0,ReviveTeammate = 0,IsAutoTurn = 1,NpcSceneType = 0,IsSnarlInFight = 1,DialogIdleTime = 320,}
g_AIParam[6520] = {IsPositive = 1,AlertRange = 768,SearchPlayerDistance = 768,AlertOverTime = 32,AttackRange = 256,EscapeTime = 64,EscapeRange = 0,EscapeInterval = 32,WanderRange = 0,WanderDistance = 384,WanderInterval = 80,PatrolPathID = 0,EscapeLife = 0,PatrolOrderIndex = 0,ReviveTeammate = 0,IsAutoTurn = 1,NpcSceneType = 0,IsSnarlInFight = 1,DialogIdleTime = 320,}
g_AIParam[6577] = {IsPositive = 0,AlertRange = 768,SearchPlayerDistance = 768,AlertOverTime = 32,AttackRange = 256,EscapeTime = 64,EscapeRange = 0,EscapeInterval = 32,WanderRange = 0,WanderDistance = 384,WanderInterval = 80,PatrolPathID = 0,EscapeLife = 0,PatrolOrderIndex = 0,ReviveTeammate = 0,IsAutoTurn = 1,NpcSceneType = 0,IsSnarlInFight = 0,DialogIdleTime = 320,}
g_AIParam[6580] = {IsPositive = 0,AlertRange = 768,SearchPlayerDistance = 768,AlertOverTime = 32,AttackRange = 256,EscapeTime = 64,EscapeRange = 0,EscapeInterval = 32,WanderRange = 0,WanderDistance = 384,WanderInterval = 80,PatrolPathID = 0,EscapeLife = 0,PatrolOrderIndex = 0,ReviveTeammate = 0,IsAutoTurn = 1,NpcSceneType = 0,IsSnarlInFight = 0,DialogIdleTime = 320,}
g_AIParam[56115] = {IsPositive = 0,AlertRange = 768,SearchPlayerDistance = 768,AlertOverTime = 32,AttackRange = 256,EscapeTime = 64,EscapeRange = 0,EscapeInterval = 32,WanderRange = 0,WanderDistance = 384,WanderInterval = 80,PatrolPathID = 0,EscapeLife = 0,PatrolOrderIndex = 0,ReviveTeammate = 0,IsAutoTurn = 1,NpcSceneType = 0,IsSnarlInFight = 0,DialogIdleTime = 320,}

 -- by 每天涨停@梦江南 $ Jx3UnPack-PAKV3 jx3.mail@gmail.com